### ISSUE TITLE
testing the bot

### ISSUE THREAD

**Issue by sanitariu** [Errorname/october-eu-bot#6]
Do the bot check for available money or not ?
I see the following then run it:

october-eu-bot $ npm run cli

> october-eu-bot@1.0.0 cli /home/dri/miner/october-eu-bot
> node src/usage/cli.js

👌 User session is correctly set up!
🔍 2 available projects found...
💰 0 lending actions with strategy "THRESHOLD(6,20)"!

How to see the projects if i want to ?
Why the but took no actions ?
I tried playing with threshold and only 2 projects found.

**Comment by Errorname** [comment]
Hi @sanitariu 
Yes, the bot checks for available money in your wallet. There is currently not an option to see the projects (except looking at app.october.eu). If the bot took no action, it is because applying your strategy to available projects returned false everytime.

Currently, there is 2 available projects on October, with 2% interest. If you want the bot to invest on them, try the "THRESHOLD(2,20)" strategy (2% min interest, with 20€ investment)

**Comment by sanitariu** [comment]
Thank you ! I tested with lower and seems okay.
